############################################################
#
# gateway 网关
# web访问端口号  约定：7888
#
############################################################
server:
  port: 7888
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: service-article
          uri: lb://SERVICE-ARTICLE
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka:7000/eureka/     #注册中心的服务地址，高可用集群则配置多个地址
test:
  test1: 50